parameters:
  pahkat_macos: "https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat-macos"
  pahkat_win: "https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat.exe"
  kbdgen_macos: "https://github.com/divvun/kbdgen/releases/download/v2.0.0-alpha.9/kbdgen_2.0.0-alpha.9_macos_amd64.tar.xz"
  kbdgen_linux: "https://github.com/divvun/kbdgen/releases/download/v2.0.0-alpha.9/kbdgen_2.0.0-alpha.9_linux_amd64.tar.xz"
  kbdgen_win: "https://github.com/divvun/kbdgen/releases/download/v2.0.0-alpha.9/kbdgen_2.0.0-alpha.9_windows_amd64.exe"

jobs:
  # - template: "sub/keyboards-desktop.yml"
  #   parameters:
  #     ${{ insert }}: ${{ parameters }}
  - template: "sub/keyboards-mobile.yml"
    parameters:
      embedSpellers: false
      ${{ insert }}: ${{ parameters }}