[package]
name = "__NAME__"
human_name = "__HUMAN_NAME__"
version = "__VERSION__"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.__NAME__]
filename = "__TAG__-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-__NAME__"
platform = "windows"
uuid = "__UUID__"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.__TAG__"
package = "speller-__NAME__"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-__NAME__-mso"
platform = "windows"
uuid = "__UUID__"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-__NAME__"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
